[package]
name = "weechat"
version = "0.1.0"
authors = [
    "KokaKiwi <kokakiwi@kokakiwi.net>",
    "Damir Jelić <poljar@termina.org.uk>"
]
description = "Weechat API bindings for Rust"
license = "MIT"

[dependencies]
libc = "0.2.48"
weechat-sys = "0.1.0"
