[package]
name = "weechat"
version = "0.1.0"
authors = [
    "KokaKiwi <kokakiwi@kokakiwi.net>",
    "Damir Jelić <poljar@termina.org.uk>"
]

repository = "https://github.com/poljar/rust-weechat/"
homepage = "https://github.com/poljar/rust-weechat/"
edition = "2018"

description = "Weechat API bindings for Rust"
license = "MIT"

[features]
async-executor = ["async-task", "pipe-channel", "futures"]

[dependencies]
libc = "0.2.66"
async-task = { version = "1.2.1", optional = true }
pipe-channel = { version = "1.2.2", optional = true }
futures = { version = "0.3.0", optional = true }

weechat-macro = { path = "../weechat-macro" }
weechat-sys = { path = "../weechat-sys" }
