language: rust
rust: stable

jobs:
  include:
    - os: linux
      dist: bionic

    - os: osx

    - os: linux
      rust: nightly
      script:
          - cargo build --all-features
          - cargo test --all-features
          - cd weechat-rs/examples
          - cd go
          - cargo build
          - cd ..
          - cd sample
          - cargo build

before_script:
  - rustup component add rustfmt

script:
  - cargo build
  - cargo fmt --all -- --check
  - cargo test
