language: rust
rust: stable

jobs:
  include:
    - os: linux
      dist: bionic

    - os: osx

before_script:
  - rustup component add rustfmt

script:
  - cargo build --all-features
  - cargo fmt --all -- --check
  - cargo test --all-features
