[package]
name = "weechat"
version = "0.1.0"
authors = [
    "KokaKiwi <kokakiwi@kokakiwi.net>",
    "Damir Jelić <poljar@termina.org.uk>"
]
description = "Weechat API bindings for Rust"
license = "MIT"

[build-dependencies]
bindgen = "*"

[dependencies]
libc = "*"
