[package]
name = "weechat-rust-sample-plugin"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"

[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
weechat = { path = "../.." }

[workspace]
