[package]
name = "weechat-rust-sample-plugin"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"

[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.72"
weechat = { path = "../.." }
weechat-sys = { path = "../../../weechat-sys" }

[workspace]
