[package]
name = "weechat-sys"
version = "0.1.0"
authors = [
    "KokaKiwi <kokakiwi@kokakiwi.net>",
    "Damir Jelić <poljar@termina.org.uk>"
]
description = "Rust low level API bindings for Weechat"
license = "MIT"

[build-dependencies]
bindgen = "*"

[dependencies]
libc = "*"
