[package]
name = "weechat-macro"
version = "0.2.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "Procedural macros for the weechat crate"
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/poljar/rust-weechat"

[lib]
proc-macro = true

[dependencies]
libc = "0.2.72"
syn = "1.0.34"
proc-macro2 = "1.0.18"
quote = "1.0.7"

[dev-dependencies]
weechat = { path = "../weechat" }
