[package]
name = "weechat-macro"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
libc = "0.2.70"
syn = "1.0.22"
proc-macro2 = "1.0.13"
quote = "1.0.6"
